package entity.subclasses;

import entity.superclasses.Person;

import java.time.LocalDate;
import java.util.Objects;
import java.util.UUID;

/**
 * User class containing extend data related to user's like subscriber card ID
 * @author erik
 * @version 1.0
 */

public final class User extends Person {
    private final UUID subscriberID;

    /**
     * Constructs a new user based on data from the builder pattern
     *
     * @param builder builder pattern containing parameters defined bellow
     */
    private User(UserBuilder builder) {
        this.oib = builder.oib;
        this.surname = builder.surname;
        this.name = builder.name;
        this.email = builder.email;
        this.phoneNumber = builder.phoneNumber;
        this.dateOfBirth = builder.dateOfBirth;
        this.subscriberID = builder.subscriberID;
    }

    /**
     * Get user's subscriber card ID
     *
     * @return UUID of the card
     */
    public UUID getSubscriberID() {
        return subscriberID;
    }

    /**
     * Overriding toString to give out a formatted user
     *
     * @return Returns a formatted string of the user
     */
    @Override
    public String toString() {
        return "User Name: " + this.name + "\tUser Surname: " + this.surname + "\tUser Card/SubscriberID: " + this.subscriberID + "\tUser Email: " + this.email + "\tUser DateOfBirth: " + this.dateOfBirth;
    }

    /**
     * Subclass implementing a builder pattern to ease the creation of a user object when having optional parameter
     * <p>
     * Required fields:
     * <ul>
     *     <li>OIB</li>
     *     <li>Name</li>
     *     <li>Surname</li>
     * </ul>
     * <p>
     * Optional fields:
     * <ul>
     *     <li>Card ID (random generated by default)</li>
     *     <li>Email</li>
     *     <li>Phone number</li>
     *     <li>Date of birth (set to unix EPOCH)</li>
     * </ul>
     */
    public static class UserBuilder {
        private final String oib;
        private final String name;
        private final String surname;

        private UUID subscriberID = UUID.randomUUID();
        private String email = "";
        private String phoneNumber = "";
        private LocalDate dateOfBirth = LocalDate.EPOCH;

        /**
         * Constructs a new builder pattern object with only the required parameters
         *
         * @param oib     String user's OIB
         * @param name    String user's first name
         * @param surname String user's last name
         * @throws NullPointerException when one or more parameters is null
         */
        public UserBuilder(String oib, String name, String surname) {
            this.oib = Objects.requireNonNull(oib, "oib must not be null");
            this.name = Objects.requireNonNull(name, "name must not be null");
            this.surname = Objects.requireNonNull(surname, "surname must not be null");
        }

        /**
         * Set optional parameter email.
         *
         * @param email String user's email
         * @return this builder
         * @throws NullPointerException if email is null
         */
        public UserBuilder email(String email) {
            this.email = Objects.requireNonNull(email, "email must not be null");
            return this;
        }

        /**
         * Set optional parameter phoneNumber.
         *
         * @param phoneNumber String user's phone number
         * @return this builder
         * @throws NullPointerException if phoneNumber is null
         */
        public UserBuilder phoneNumber(String phoneNumber) {
            this.phoneNumber = Objects.requireNonNull(phoneNumber, "phoneNumber must not be null");
            return this;
        }

        /**
         * Set optional parameter dateOfBirth.
         *
         * @param dateOfBirth LocalDate user's date of birth
         * @return this builder
         * @throws NullPointerException if dateOfBirth is null
         */
        public UserBuilder dateOfBirth(LocalDate dateOfBirth) {
            Objects.requireNonNull(dateOfBirth, "dateOfBirth must not be null");
            this.dateOfBirth = dateOfBirth;
            return this;
        }

        /**
         * Set optional parameter subscriber card UUID.
         *
         * @param subscriberID driver's date of birth
         * @return this builder
         * @throws NullPointerException if dateOfBirth is null
         */
        public UserBuilder subscriberID(UUID subscriberID) {
            this.subscriberID = Objects.requireNonNull(subscriberID, "subscriberID must not be null");
            return this;
        }

        /**
         * Calls the constructor of the user class
         * @return returns new object of user, with all parameters set up
         */
        public User build() {
            return new User(this);
        }
    }
}
